using System.Collections.Generic;

namespace OrbinatAPI.Models
{
    public static class Database
    {
        public static List<CompanyProfile> GetAllCompanies()
        {
            return new List<CompanyProfile>
            {
                new CompanyProfile { Name = "Orbital Dynamics",ImageUrl = "OrbitalDynamics.jpg", HasOBC=true, HasEPS=true, HasADCS=true, HasCOMMS=true, HasPayload=true, HasThermalTest=true, HasVibrationTest=true, ExperienceLevel="High", BudgetLevel="High", MissionFit="Earth Observation", TotalMissions=45, SuccessRate=98.5, DeliveryTime="Fast", MassKg=1.1, Reliability="High" },
                new CompanyProfile { Name = "NovaSpace Systems",ImageUrl ="NovaSpaceSystems.jpg", HasOBC=true, HasEPS=true, HasADCS=false, HasCOMMS=true, HasPayload=false, HasThermalTest=false, HasVibrationTest=false, ExperienceLevel="Medium", BudgetLevel="Medium", MissionFit="Communication", TotalMissions=12, SuccessRate=85.0, DeliveryTime="Medium", MassKg=1.3, Reliability="Medium" },
                new CompanyProfile { Name = "AstroLink Technologies",ImageUrl ="AstroLinkTechnologies.jpg", HasOBC=true, HasEPS=false, HasADCS=true, HasCOMMS=true, HasPayload=false, HasThermalTest=false, HasVibrationTest=false, ExperienceLevel="Medium", BudgetLevel="Low", MissionFit="Communication", TotalMissions=8, SuccessRate=75.0, DeliveryTime="Slow", MassKg=1.5, Reliability="Medium" },
                new CompanyProfile { Name = "Celestial Labs",ImageUrl ="CelestialLabs.jpg", HasOBC=false, HasEPS=true, HasADCS=true, HasCOMMS=false, HasPayload=true, HasThermalTest=true, HasVibrationTest=true, ExperienceLevel="Medium", BudgetLevel="Medium", MissionFit="Earth Observation", TotalMissions=20, SuccessRate=92.0, DeliveryTime="Medium", MassKg=1.2, Reliability="Medium" },
                new CompanyProfile { Name = "SkyForge Aerospace",ImageUrl ="SkyForgeAerospace.jpg", HasOBC=true, HasEPS=true, HasADCS=true, HasCOMMS=false, HasPayload=false, HasThermalTest=false, HasVibrationTest=false, ExperienceLevel="Medium", BudgetLevel="Low", MissionFit="Tech Demo", TotalMissions=3, SuccessRate=66.6, DeliveryTime="Fast", MassKg=0.9, Reliability="Low" },
                new CompanyProfile { Name = "StellarCore Engineering",ImageUrl = "StellarCoreEngineering.jpg", HasOBC=true, HasEPS=true, HasADCS=true, HasCOMMS=true, HasPayload=false, HasThermalTest=true, HasVibrationTest=true, ExperienceLevel="High", BudgetLevel="High", MissionFit="Earth Observation", TotalMissions=38, SuccessRate=95.0, DeliveryTime="Fast", MassKg=1.0, Reliability="High" },
                new CompanyProfile { Name = "CosmoWorks",ImageUrl = "CosmoWorksjpg", HasOBC=false, HasEPS=true, HasADCS=false, HasCOMMS=true, HasPayload=true, HasThermalTest=false, HasVibrationTest=false, ExperienceLevel="Low", BudgetLevel="Low", MissionFit="Research", TotalMissions=1, SuccessRate=100.0, DeliveryTime="Slow", MassKg=1.4, Reliability="Low" },
                new CompanyProfile { Name = "AetherSpace",ImageUrl = "AetherSpace.jpg", HasOBC=true, HasEPS=false, HasADCS=true, HasCOMMS=false, HasPayload=false, HasThermalTest=false, HasVibrationTest=false, ExperienceLevel="Low", BudgetLevel="Low", MissionFit="Tech Demo", TotalMissions=0, SuccessRate=0.0, DeliveryTime="Medium", MassKg=1.3, Reliability="Low" },
                new CompanyProfile { Name = "Orbitronix",ImageUrl = "Orbitronix.jpg",HasOBC=true, HasEPS=true, HasADCS=true, HasCOMMS=true, HasPayload=true, HasThermalTest=false, HasVibrationTest=false, ExperienceLevel="High", BudgetLevel="Medium", MissionFit="Earth Observation", TotalMissions=25, SuccessRate=88.0, DeliveryTime="Fast", MassKg=1.2, Reliability="High" },
                new CompanyProfile { Name = "Zenith Space Solutions",ImageUrl = "ZenithSpaceSolutions.jpg", HasOBC=false, HasEPS=false, HasADCS=true, HasCOMMS=true, HasPayload=false, HasThermalTest=true, HasVibrationTest=true, ExperienceLevel="Medium", BudgetLevel="Medium", MissionFit="Communication", TotalMissions=15, SuccessRate=93.5, DeliveryTime="Medium", MassKg=1.3, Reliability="Medium" },
                new CompanyProfile { Name = "HyperNova Systems",ImageUrl = "HyperNovaSystems.jpg", HasOBC=true, HasEPS=true, HasADCS=false, HasCOMMS=true, HasPayload=true, HasThermalTest=true, HasVibrationTest=false, ExperienceLevel="Medium", BudgetLevel="High", MissionFit="Earth Observation", TotalMissions=18, SuccessRate=89.0, DeliveryTime="Fast", MassKg=1.1, Reliability="High" },
                new CompanyProfile { Name = "LunaTech Industries",ImageUrl = "LunaTechIndustries.jpg" ,HasOBC=true, HasEPS=false, HasADCS=false, HasCOMMS=true, HasPayload=true, HasThermalTest=false, HasVibrationTest=false, ExperienceLevel="Low", BudgetLevel="Low", MissionFit="Tech Demo", TotalMissions=4, SuccessRate=50.0, DeliveryTime="Slow", MassKg=1.5, Reliability="Low" },
                new CompanyProfile { Name = "VectorSpace Labs" ,ImageUrl = "VectorSpaceLabs.jpg", HasOBC=false, HasEPS=true, HasADCS=true, HasCOMMS=false, HasPayload=false, HasThermalTest=true, HasVibrationTest=true, ExperienceLevel="Medium", BudgetLevel="Medium", MissionFit="Research", TotalMissions=10, SuccessRate=80.0, DeliveryTime="Medium", MassKg=1.2, Reliability="Medium" },
                new CompanyProfile { Name = "AstroBridge",ImageUrl = "AstroBridge.jpg", HasOBC=true, HasEPS=true, HasADCS=true, HasCOMMS=true, HasPayload=false, HasThermalTest=false, HasVibrationTest=true, ExperienceLevel="High", BudgetLevel="High", MissionFit="Earth Observation", TotalMissions=30, SuccessRate=96.5, DeliveryTime="Fast", MassKg=1.0, Reliability="High" },
                new CompanyProfile { Name = "Kepler Innovations",ImageUrl = "KeplerInnovations.jpg", HasOBC=true, HasEPS=true, HasADCS=false, HasCOMMS=false, HasPayload=true, HasThermalTest=false, HasVibrationTest=false, ExperienceLevel="Medium", BudgetLevel="Medium", MissionFit="Research", TotalMissions=7, SuccessRate=71.4, DeliveryTime="Medium", MassKg=1.3, Reliability="Medium" }
            };
        }
    }
}